import json
from pathlib import Path
from typing import Any, Dict, Tuple
from .parser import HCLParser

class HCLCompiler:
    """Compiles Declarative Governance HCL into BPF maps, SCITT schemas, and SQLite WAL rules."""

    def __init__(self, ast: Dict[str, Any]):
        self.ast = ast

    @classmethod
    def from_file(cls, filepath: str) -> "HCLCompiler":
        text = Path(filepath).read_text(encoding="utf-8")
        parser = HCLParser(text)
        ast = parser.parse()
        return cls(ast)

    def compile_all(self, out_dir: str) -> Dict[str, str]:
        p = Path(out_dir)
        p.mkdir(parents=True, exist_ok=True)

        bpf_h, bpf_json = self.compile_bpf_maps()
        scitt_schema = self.compile_scitt_schema()
        wal_sql = self.compile_sqlite_wal_invariants()

        (p / "bpf_maps.h").write_text(bpf_h, encoding="utf-8")
        (p / "admissibility_table.json").write_text(json.dumps(bpf_json, indent=2), encoding="utf-8")
        (p / "scitt_policy_schema.json").write_text(json.dumps(scitt_schema, indent=2), encoding="utf-8")
        (p / "wal_invariants.sql").write_text(wal_sql, encoding="utf-8")

        return {
            "bpf_maps_header": str(p / "bpf_maps.h"),
            "admissibility_table": str(p / "admissibility_table.json"),
            "scitt_schema": str(p / "scitt_policy_schema.json"),
            "wal_invariants": str(p / "wal_invariants.sql")
        }

    def compile_bpf_maps(self) -> Tuple[str, Dict[str, Any]]:
        boundary = self.ast.get("network_boundary", {})
        # Find first mesh or boundary configuration
        boundary_cfg = list(boundary.values())[0] if isinstance(boundary, dict) and boundary else {}
        allowed_ports = boundary_cfg.get("allowed_ports", [8080])

        bpf_header = f"""// Auto-generated by SMAOS HCL Governance Compiler
// Target: Linux Ring-0 eBPF / XDP LSM Kernel Membrane
#ifndef __SMAOS_BPF_MAPS_H
#define __SMAOS_BPF_MAPS_H

#include <linux/types.h>
#include <bpf/bpf_helpers.h>

#define ADMISSIBILITY_MAX_PORTS {len(allowed_ports)}

struct {{
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 256);
    __type(key, __u16);
    __type(value, __u32);
}} admissibility_ports SEC(".maps");

static const __u16 ALLOWED_PORTS[ADMISSIBILITY_MAX_PORTS] = {{
    {", ".join(str(p) for p in allowed_ports)}
}};

#endif // __SMAOS_BPF_MAPS_H
"""
        table_json = {
            "version": "1.0.0",
            "egress_mode": self.ast.get("system", {}).get("smaos_governance", {}).get("egress_mode", "zero_egress"),
            "allowed_ports": allowed_ports,
            "bpf_lsm_drop": boundary_cfg.get("bpf_lsm_drop", True),
            "drop_icmp": boundary_cfg.get("drop_icmp", True),
            "max_ingress_rate_kbps": boundary_cfg.get("max_ingress_rate_kbps", 10000)
        }
        return bpf_header, table_json

    def compile_scitt_schema(self) -> Dict[str, Any]:
        scitt_cfg = self.ast.get("scitt_policy", {})
        policy = list(scitt_cfg.values())[0] if isinstance(scitt_cfg, dict) and scitt_cfg else {}
        allowed_algs = policy.get("allowed_algs", ["EdDSA"])
        profile = policy.get("profile", "draft-ietf-scitt-architecture-04")

        return {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "title": "SMAOS_SCITT_Policy_Validation_Schema",
            "type": "object",
            "required": ["protected_header", "payload_hash", "signature_base64", "payload"],
            "properties": {
                "protected_header": {
                    "type": "object",
                    "required": ["alg", "profile"],
                    "properties": {
                        "alg": {"type": "string", "enum": allowed_algs},
                        "profile": {"type": "string", "const": profile}
                    }
                },
                "payload_hash": {
                    "type": "string",
                    "pattern": "^[a-f0-9]{64}$"
                },
                "signature_base64": {
                    "type": "string",
                    "minLength": 32
                }
            }
        }

    def compile_sqlite_wal_invariants(self) -> str:
        isolation = self.ast.get("isolation", {}).get("sqlite_wal", {})
        journal_mode = isolation.get("journal_mode", "WAL")
        synchronous = isolation.get("synchronous", "NORMAL")

        agent_block = self.ast.get("agent", {})
        agent_cfg = list(agent_block.values())[0] if isinstance(agent_block, dict) and agent_block else {}
        max_val = agent_cfg.get("max_transaction_value", 1000000.0)

        sql = f"""-- Auto-generated by SMAOS HCL Governance Compiler
-- Enforces SQLite Write-Ahead Logging (WAL) Copy-on-Write (CoW) Invariants
PRAGMA journal_mode = {journal_mode};
PRAGMA synchronous = {synchronous};

CREATE TABLE IF NOT EXISTS intent_cow_branches (
    branch_id TEXT PRIMARY KEY,
    parent_id TEXT,
    agent_id TEXT NOT NULL,
    transaction_value REAL,
    status TEXT NOT NULL CHECK (status IN ('PENDING', 'ALLOWED', 'DENIED', 'UNKNOWN', 'CONFIRMED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER IF NOT EXISTS trg_intent_fail_closed_policy
BEFORE INSERT ON intent_cow_branches
FOR EACH ROW
BEGIN
    SELECT CASE
        WHEN NEW.transaction_value > {max_val}
        THEN RAISE(ABORT, '[SMAOS_POLICY_VIOLATION] Transaction value exceeds HCL declared limit')
    END;
END;

CREATE TRIGGER IF NOT EXISTS trg_intent_deny_rollback
AFTER UPDATE OF status ON intent_cow_branches
FOR EACH ROW
WHEN NEW.status = 'DENIED' OR NEW.status = 'UNKNOWN'
BEGIN
    DELETE FROM intent_cow_branches WHERE branch_id = NEW.branch_id;
END;
"""
        return sql
